# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2023.10.27
_src_path: gh:scientific-python/cookie
backend: hatch
email: nagacharan.tangirala@tum.de
full_name: Nagacharan Teja Tangirala
license: MIT
org: nagacharan-tangirala
project_name: prep-pavenet
project_short_description: The positions for disolv are prepared by this project.
url: https://github.com/nagacharan-tangirala/disolv-positions
vcs: true
